config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|ru/ do
    match 'post', to: 'posts#index', as: 'post', via: 'get'
    match 'post/:id', to: 'posts#show', via: 'get'
    match 'audiomessage', to: 'order_audio#new', as: 'new_order_audios', via: 'get'
    match 'audiomessage', to: 'order_audio#create', as: 'order_audios', via: 'post'
  end

  devise_for :users

  namespace :admin do
    root 'dashboard#show'
    resources :posts, except: 'show'
    resources :order_audio, except: %w{ new edit create } do
      member do
        post :success
        post :restore
      end
    end
  end

  get '/:locale' => 'title#show'
  root 'title#show'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/order_audio.rb
class OrderAudio < ActiveRecord::Base
  validates :subject, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :text, presence: true, length: { minimum: 20 }



end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true

  has_many :ckeditor_assets

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
end

app/controllers/admin/order_audio_controller.rb
class Admin::OrderAudioController < ApplicationController

  layout 'admin'
  before_action :authenticate_user!
  before_action :find_order, only: %w(success restore)

  def index
    @orders = OrderAudio.all.order('created_at DESC').where(success: false)
    @success = OrderAudio.all.order('created_at DESC').where(success: true)
  end

  def show
    @order = OrderAudio.find(params[:id])
  end

  def destroy
    @order = OrderAudio.find(params[:id])
    @order.destroy

    redirect_to '/admin/order_audio'
  end
=begin
  def update
    @order = OrderAudio.find(params[:id])

    if @order.update(order_params)
      redirect_to '/admin/order_audio'
    else
      render 'show'
    end
  end
=end
  def success
    @order.update_attribute :success, true
    redirect_to '/admin/order_audio'
  end

  def restore
    @order.update_attribute :success, false
    redirect_to '/admin/order_audio'
  end

private

  def order_params
    params.require(:order_audio).permit(:success)
  end

  def find_order
    @order = OrderAudio.find params[:id]
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    redirect_to '/admin/posts'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to '/admin/posts'
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to '/admin/posts'
    else
      render 'edit'
    end
  end

private

  def post_params
    params.require(:post).permit(:title, :description, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end
end

app/controllers/order_audio_controller.rb
class OrderAudioController < ApplicationController
  def new
    @order = OrderAudio.new
  end

  def create
    @order = OrderAudio.create(order_params)
      if @order.save
        redirect_to root_path
        flash[:notice] = "Order was been save"
      else
        render 'new'
      end
  end

private

  def order_params
    params.require(:order_audio).permit(:subject, :email, :text)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find params[:id]
  end

  def timeago(time, options = {})
    options[:class] ||= "timeago"
    content_tag(:abbr, time.to_s, options.merge(:title => time.getutc.iso8601)) if time
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def show
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/order_audio_helper.rb
module Admin::OrderAudioHelper
  def set_success_btn(order)
    if order.success?
      link_to 'восстановить',
              restore_admin_order_audio_path(order),
              class: 'btn btn-success btn-mini',
              method: :post
    else
      link_to 'Выполнено',
              success_admin_order_audio_path(order),
              class: 'btn btn-warning btn-mini',
              method: :post
    end
  end

  def destroy_btn(order)
    if order.success?
      link_to 'Удалить',
              admin_order_audio_path(order),
              class: 'btn btn-success btn-mini',
              method: :delete,
              confirm: "Вы уверены?"
            end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title_page
    title = content_for?(:title) ? content_for(:title) : nil
    title ? t('views.title.title', title: title.chomp) : t('views.title.title')
  end
end

app/helpers/order_audio_helper.rb
module OrderAudioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/admin/dashboard/show.html.slim
h2 Привет, Василий :)

app/views/admin/order_audio/index.html.slim
//Nav tabs
div(role="tabpanel")
  ul.nav.nav-tabs(role="tablist")
    li.active(role="presentation")
      a(href="#new" aria-controls="new" role="tab" data-toggle="tab") Новые
    li(role="presentation")
      a(href="#success" aria-controls="success" role="tab" data-toggle="tab")  Выполненные

  .tab-content
    .tab-pane.fade.in.active#new
      - if @orders.any?
        table.table.table-striped
          thead
            tr
              th Тема
              th Email
              th(colspan="2")
          tbody
            - @orders.each do |order|
              tr
                td = link_to order.subject, admin_order_audio_path(order)
                td
                  a(href="mailto:#{order.email}") = order.email
                td = set_success_btn order
      - else
        h3 Нет невыполненных заявок.
    .tab-pane.fade#success
      - if @success.any?
        table.table.table-striped
          thead
            tr
              th Тема
              th Email
              th(colspan="2")
          tbody
            - @success.each do |order|
              tr
                td = link_to order.subject, admin_order_audio_path(order)
                td
                  a(href="mailto:#{order.email}") = order.email
                td = set_success_btn order
                td = destroy_btn order
      - else
        h3 Нет выполненных заявок.

app/views/admin/order_audio/show.html.slim
div.pull-right
  = set_success_btn @order

h3 = @order.subject
p = @order.email
p = @order.text

app/views/admin/posts/_form.html.slim
= simple_form_for @post, url: [:admin, @post] do |f|
  = f.input :title
  = f.input :description,  :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Pure'} }
  // f.input :text, input_html: { class: 'input-xxlarge redactor' }
  = f.input :text, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }
  = f.button :submit

app/views/admin/posts/edit.html.slim
= render partial: 'form'

app/views/admin/posts/index.html.slim
= link_to 'Создать запись', new_admin_post_path, class: "btn btn-primary"

- if @posts.any?
  table.table.table-striped
    thead
      tr
        th Заголовок
        th Краткое описание
        th(colspan="2")
    tbody
      - @posts.each do |post|
        tr
          td = post.title
          td == strip_tags post.description
          td = link_to 'Редактировать', edit_admin_post_path(post)
          td = link_to 'Удалить', admin_post_path(post), method: :delete, data: { confirm: 'Вы уверены?' }

app/views/admin/posts/new.html.slim
= render partial: 'form'

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title_page %></title>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <nav class="nav navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <%= link_to 'Admin panel', admin_root_path, class: "navbar-brand" %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to 'Go to Main page', root_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <aside class="col-xs-4">
          <ul class="nav nav-vertical">
            <li class="nav-header"> Разделы</li>
            <li><%= link_to "#{t ('views.nav.blog')}", admin_posts_path %></li>
            <li><%= link_to "#{t ('views.nav.audiomessages')}", admin_order_audio_index_path %></li>
          </ul>
        </aside>
        <div class="col-xs-8">
        <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title_page %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
<div class="content"></div>
<%= yield %>

</body>
</html>

app/views/order_audio/new.html.slim
= render 'partials/nav'

.container.wrapper
  .row
    .col-xs-12.col-md-8
      .form_block
        = simple_form_for @order do |f|
          = f.input :subject
          = f.input :email, input_html: { class: 'input-xxlarge redactor' }
          = f.input :text
          = f.button :submit

app/views/partials/_nav.html.slim
nav.navbar.navbar-fixed-top(role="navigation")
  .container-fluid.nav_ui
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to "#{t ('views.nav.mainpage')}", root_path
        li
          = link_to "#{t ('views.nav.press')}", post_path
        li
          a(href="") = t ('views.nav.seasons')
        li
          a(href="") = t ('views.nav.global')
        li
          a(href="") = t ('views.nav.memcards')
        li
          = link_to "#{t ('views.nav.audiomessages')}", new_order_audios_path
        li
          = link_to "#{t ('views.nav.blog')}", post_path
        li
          a(href="") = t ('views.nav.links')

app/views/posts/index.html.slim
= render 'partials/nav'

.container.wrapper
  .row
    .col-xs-12.col-md-8
      h1
        = t ('views.posts.title')
    .col-xs-12.col-md-8
      - if @posts.present?
        - @posts.each do |post|
          .post
            h2 = link_to post.title, controller: "posts", action: "show", id: post
            p == post.description
            abbr.timeago(title="#{post.created_at.getutc.iso8601}") = post.created_at.to_s
      - else
        .post
          h2 = t ('views.posts.empty')

app/views/posts/show.html.slim
= render 'partials/nav'

.container.wrapper
  .row
    .col-xs-12.col-md-8
      h1
        = @post.title
    .col-xs-12.col-md-8.background_post
      .post.current
        == @post.text

      = link_to "#{t ('views.nav.back')}", post_path, class: "btn btn-link"

app/views/title/show.html.slim
header.head.logo
  h1 = t ('views.title.title')
nav.main_nav
  ul
    li
      a(href="") = t ('views.nav.press')
    li
      a(href="") = t ('views.nav.seasons')
    li
      a(href="") = t ('views.nav.global')
    li
      a(href="") = t ('views.nav.memcards')
    li
      = link_to "#{t ('views.nav.audiomessages')}", new_order_audios_path
    li
      = link_to "#{t ('views.nav.blog')}", post_path
    li
      a(href="") = t ('views.nav.links')

footer.navbar.navbar-default.navbar-fixed-bottom
  .container.footer
    .row
      .col-xs-6
        = link_to "|RU", root_path(locale: :ru)
        = link_to "|EN|", root_path(locale: :en)